replicaCount: 3

image:
  repository: cassizx/hello_world_go
  pullPolicy: IfNotPresent
  tag: "docker"
  # tag: "hello_world_go-0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  # runAsNonRoot: true
  # runAsUser: 1000
  # readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: hello-go.alexkv.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-go-alexkv-dev
      hosts:
        - hello-go.alexkv.dev

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
